### ISSUE TITLE
Did not receive resources from settlements built on hexes in setup round

### ISSUE THREAD

**Issue by klew91** [cs340tabyu/cs340Winter2017#743] opened 2016-11-18 21:41 UTC
You are supposed to get resources from the hexes adjacent to the settlements you build during the setup round.
https://gyazo.com/d572d27fd55646c916b24fe4c1a63790

**Comment by irbishop** [comment] 2016-11-21 19:10
Duplicate of #674

**Closed as completed** 2016-11-21 19:11 UTC
Labels: Duplicate, P4: Incorrect behavior that doesn't affect gameplay, Phase 3, Team 18
