### ISSUE TITLE
Robber Does Not Block Resource Generation

### ISSUE THREAD

**Issue by wfearn** [cs340tabyu/cs340Winter2017#612] opened 2016-11-18 18:46 UTC
I had a city on a wheat hex with token number 6 which had the robber on it. After rolling a 6 that player who had a city on the wheat hex had two more wheat.

**Comment by UnoriginalElephant** [comment] 2016-11-18 19:03
duplicate of #611

**Closed as completed** 2016-11-22 20:08 UTC
Labels: Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 3, TA-Fixed, Team 9
