### ISSUE TITLE
Place Road/Settlement overlay flashes rapidly

### ISSUE THREAD

**Issue by SierraD012** [cs340tabyu/cs340Winter2017#418] opened 2016-10-27 04:27 UTC
While in setup phase, the place road/settlement overlay shows the map with my buildings on it but it flashes randomly a few times a second. This makes it really hard to tell where I'm placing the buildings.

**Comment by dansteren** [comment] 2016-10-28 16:38
This is a duplicate of #318. Follow this issue on that thread.

**Closed as completed** 2016-10-28 16:39 UTC
Labels: Duplicate, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 12
