### ISSUE TITLE
Monument Card Not Available For Play Upon Buying

### ISSUE THREAD

**Issue by wfearn** [cs340tabyu/cs340Winter2017#610] opened 2016-11-18 18:38 UTC
I bought a monument card, and I wasn't immediately able to play it. When my next turn came around I still was unable to play it (The picture was grayed out).

**Comment by UnoriginalElephant** [comment] 2016-11-18 18:58
This is a duplicate of #608.  Please check for duplicates before logging

**Closed as completed** 2016-11-21 22:23 UTC
Labels: Duplicate, Invalid, P3: Incorrect behavior that affects gameplay, Phase 3, Team 9
