### ISSUE TITLE
Domestic trade button is enabled even when it isn't the user's turn

### ISSUE THREAD

**Issue by athompson909** [cs340tabyu/cs340Winter2017#297] opened 2016-10-27 01:25 UTC
the domestic trade button should be disabled if it isn't the user's turn

**Comment by dansteren** [comment] 2016-10-31 16:50
Here's our current code:

```
int currentTurn = (int) getIn(clientModel, "turnTracker", "currentTurn");
boolean isClientPlayerTurn = eq(clientPlayerIndex, currentTurn);
getTradeView().enableDomesticTrade(isClientPlayerTurn);
```

So, we are are checking to see if it is the user's turn. 

I think the problem is that the current turn starts out as 0. So, if you're signed in as the first player then your index matches and so the button appears enabled while you are waiting for the game to start. That's the only place where I'm not seeing the button behave like it's supposed to.

So, I think the fix for this is to simply add another check that makes sure that the game is in the playing state. With both those checks we should be in good shape.

**Closed as completed** 2016-10-31 18:08 UTC
Labels: Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 12
