### ISSUE TITLE
Cannot finish turn after rolling for the first time

### ISSUE THREAD

**Issue by melanie38** [cs340tabyu/cs340Winter2017#401] opened 2016-10-27 04:02 UTC
Works great for the two rounds of setting but after Player 1 rolls, he cannot finish turn and all the other buttons are frozen.

**Comment by cojoco** [comment] 2016-10-27 04:14
I believe this is a duplicate of #130

**Comment by cojoco** [comment] 2016-10-31 21:48
This appears to be fixed now.

**Closed as completed by cojoco** 2016-10-31 21:48 UTC
Labels: Duplicate, P2: Blocking gameplay, Phase 2, Team 7
