### ISSUE TITLE
Place a road...Again

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#447] opened 2016-10-27 05:34 UTC
I was going through the initial setup of the game and got the first road and settlement placed for each player. I then started placing the second settlements/roads. When I got back to the second player I placed a road. Then, instead of being told to place a settlement, I was told to place a road... again. It doesn't let the player get passed this.

I tried restarting the client but it didn't work. So, I just placed a nice figure 8 of roads instead.

![placearoadagain](https://cloud.githubusercontent.com/assets/5455419/19755573/24118ede-9bd4-11e6-9336-206c5c0f4e22.png)

I haven't tried reproducing this yet, but hopefully I can. Maybe it's because I was able to place a second road for player 2 already (as player 3 lol) when they were each picking their first road/settlements. Either way. I can't get past this part.

But hey, the longest road thing is working ;)

![longestroad](https://cloud.githubusercontent.com/assets/5455419/19755666/a9a3c4a4-9bd4-11e6-9030-bab6771a782b.png)

**Comment by dansteren** [comment] 2016-10-27 05:40
**Update:** Just tried this again running `java -jar catan-client.jar` (aka. pointing to your server) and the whole setup process worked great. I don't know if that's the issue, but maybe.

**Comment by ringmaster217** [comment] 2016-10-27 16:34
I can't replicate this bug at all.

**Comment by smithskyler** [comment] 2016-10-27 21:45
I haven't been able to reproduce this either, but I'm pretty sure that if this can happen, then it's caused by that invalid road placement of P3 for P2. In that case, this is a duplicate of #442.

**Closed as completed** 2016-10-31 18:18 UTC
Labels: Duplicate, Fixed, P2: Blocking gameplay, Phase 2, Team 13
