### ISSUE TITLE
Settlement Built not attached to anything after setup

### ISSUE THREAD

**Issue by irbishop** [cs340tabyu/cs340Winter2017#478] opened 2016-10-27 08:47 UTC
There is now a random puce settlement attached to green and purple roads in the upper left of the map.  The game says Squall built the settlement, however, test got the points and the building color is puce.  test got credit for building the road in the game history but the color of the road is for Squall.

![settlement](https://cloud.githubusercontent.com/assets/161021/19760666/f43547ac-9bef-11e6-8349-f41e10ba4488.png)

**Comment by abatschi** [comment] 2016-10-29 18:49
fixed

**Comment by abatschi** [comment] 2016-10-29 19:01
this is a duplicate of issue #476

**Closed as completed by abatschi** 2016-10-29 19:01 UTC
Labels: Duplicate, P3: Incorrect behavior that affects gameplay, Phase 2, Team 14
