### ISSUE TITLE
Finish turn takes five minutes to be enabled for first player

### ISSUE THREAD

**Issue by taetem** [cs340tabyu/cs340Winter2017#646] opened 2016-11-18 19:37 UTC
When several computer clients are connected, after the first player places their road and settlement, the game never progresses to the 2nd player. This bug was found with two computers connected to one server, each with 2 clients.

Update: Turns out the problem is that Finish Turn took about 5 minutes to pop up - after clicking finish turn, things work again, but the amount of time it took to pop up on the first player still significantly blocks gameplay.

**Comment by intcreator** [comment] 2016-11-18 21:06
I'm unable to duplicate this with multiple clients on my local machine.  However, instead of the player having to click "Finish Turn", we should just finish the turn once both the settlement and road have been placed (see #541).

I did note that after the first four turns (every player has placed a road and a settlement) the "Finish turn" button gets enabled for every player for two rounds and then after that it's disabled for everyone.

**Comment by intcreator** [comment] 2016-11-21 21:43
This is a duplicate of #541 and #544.

**Closed as completed** 2016-11-21 21:43 UTC
Labels: Duplicate, P2: Blocking gameplay, Phase 3, Team 12
