### ISSUE TITLE
Does not update Players List as players enter game

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#242] opened 2016-10-27 00:08 UTC
Player list does not update as players enter
![bug2](https://cloud.githubusercontent.com/assets/22157895/19749560/2ca68356-9ba7-11e6-95e1-c3058bf780e6.png)

**Comment by UnoriginalElephant** [comment] 2016-10-28 00:36
duplicate of #108

**Comment by Chroniclerz** [comment] 2016-10-28 00:37
Appears to be so.

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Duplicate, Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 9
