### ISSUE TITLE
Team 9 - P4 - Can keep playing after GameOver

### ISSUE THREAD

**Issue by Ironslacker** [cs340tabyu/cs340Winter2017#180] opened 2016-10-26 21:45 UTC
Not sure what exactly is supposed to happen after GameOver, but you can still keep playing even though the GameOver screen will keep popping up

**Comment by UnoriginalElephant** [comment] 2016-10-31 21:17
duplicate of #264

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Duplicate, Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 9
