### ISSUE TITLE
Game freezes after first player plays during the first setup round

### ISSUE THREAD

**Issue by klew91** [cs340tabyu/cs340Winter2017#735] opened 2016-11-18 21:25 UTC
Game froze after first player placed road and settlement. Had to rejoin in order to continue.

**Comment by irbishop** [comment] 2016-11-19 00:16
Was there a stack trace or any additional information you can provide?

**Comment by irbishop** [comment] 2016-11-19 00:43
Duplicate of #669

**Closed as completed by irbishop** 2016-11-19 00:43 UTC
Labels: Duplicate, P2: Blocking gameplay, Phase 3, Team 18, Unable to Replicate
