### ISSUE TITLE
Placing settlements on sea hexes crashes game

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#244] opened 2016-10-27 00:11 UTC
Settlements in the setup round can be placed on Sea Hexes. Additionally, does not continue on to place roads, nor end turn. Locks game. Closing session and logging back in undoes actio
![bug4](https://cloud.githubusercontent.com/assets/22157895/19749606/8725889a-9ba7-11e6-97b4-59150ff14432.png)
n

**Comment by HawkoftheDawn** [comment] 2016-10-31 11:18
Wrong severity?  This doesn't actually block you from playing the game... it'll crash your client session, but you don't have to be able to place a settlement on water without crashing, and even if you do, you're not hosed because reopening the client makes it like nothing ever happened.

And it's fixed.

**Comment by UnoriginalElephant** [comment] 2016-10-31 21:29
duplicate of #243

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Duplicate, Fixed, P2: Blocking gameplay, Phase 2, Team 9, Wrong Severity Classification
