### ISSUE TITLE
Dev Card bought not showing up

### ISSUE THREAD

**Issue by melanie38** [cs340tabyu/cs340Winter2017#422] opened 2016-10-27 04:35 UTC
The dev cards I bought are all greyed out. Seems like it is not updating how it should.

**Comment by cojoco** [comment] 2016-10-28 13:56
I believe this is a duplicate of #154

**Comment by cojoco** [comment] 2016-10-30 03:50
Since #154 is fixed, this should also be fixed. The dev cards are supposed to be grayed out the turn you buy them, unless they're monument cards. They should be usable the turn after.

**Closed as completed by cojoco** 2016-10-30 03:50 UTC
Labels: Fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 7
