### ISSUE TITLE
Accept the same player name to be logged

### ISSUE THREAD

**Issue by MikeCodechief** [cs340tabyu/cs340Winter2017#680] opened 2016-11-18 20:09 UTC
The program can't prevent the the another player to log in with name that is already logged.

**Comment by irbishop** [comment] 2016-11-19 00:23
This appears to be a duplicate of #659, which is invalid.  You should be able to login as the same user multiple times and play in multiple games.

**Closed as completed by irbishop** 2016-11-19 00:23 UTC
Labels: Duplicate, Invalid, P3: Incorrect behavior that affects gameplay, Phase 3, Team 18
