### ISSUE TITLE
Duplicate Games Created

### ISSUE THREAD

**Issue by dansteren** [cs340tabyu/cs340Winter2017#805] opened 2016-11-19 05:31 UTC
## Steps to reproduce:

1. Client1: Spin up one client
2. Client1: Register Player 1
3. Client1: Click "Create Game"
4. Client1: Enter a game Name
5. Client1: Click "Create Game"
6. Client2: Spin up a second client
7. Client2: Register Player 2
8. Client2: Click "Join"
9. Client1: Click cancel.
10. Client1: Click "Create Game"
11. Client1: Click "Create Game"
12. Client1: Choose a color and click "Join Game"

Both clients display 1 user in the game.

The problem that's going on here is that when a player clicks "Cancel" on the select color screen, the game has already been created but the client doesn't update to show that new game. Other client's can see it, but they can't. So then, you get two players thinking they're joining the same game, when they aren't. You should not run the create game command until the user picks a color and clicks "Join Game". Also, you should refresh your list of games automatically.

**Comment by Napper15** [comment] 2016-11-21 17:44
https://github.com/cs340tabyu/cs340fall2016/issues/685  duplicate of this because the functional spec does not specify that two games cannot have the same name (that I could find).  And so the real bug is the list of games not updating for other clients.

**Closed as completed by Napper15** 2016-11-21 17:44 UTC
Labels: Duplicate, P4: Incorrect behavior that doesn't affect gameplay, Phase 3, Team 14
