### ISSUE TITLE
Incorrect color options in join game

### ISSUE THREAD

**Issue by chaserobertson** [cs340tabyu/cs340Winter2017#163] opened 2016-10-26 21:06 UTC
Separate clients do not update color options after other users join. Default colors are always grayed out.

Joined Empty Game with White, Yellow, and Purple players. Fourth player color options included all three of those, but excluded Orange, Blue, and Green (which I believe are default colors). At this point it is allowed to join with a player of duplicate color.

Seems like a polling problem, because restarting client resets color options correctly.

**Comment by UnoriginalElephant** [comment] 2016-10-28 00:25
possibly a p4 or p5, or duplicate of issue #108

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Duplicate, Fixed, P4: Incorrect behavior that doesn't affect gameplay, Phase 2, Team 9, Wrong Severity Classification
