### ISSUE TITLE
Doesn't Award Points for Longest Road

### ISSUE THREAD

**Issue by gauntc** [cs340tabyu/cs340Winter2017#686] opened 2016-11-18 20:17 UTC
![longestroad](https://cloud.githubusercontent.com/assets/18722665/20445220/60e9a296-ad91-11e6-83fb-46deecc29187.png)

**Comment by irbishop** [comment] 2016-11-19 00:41
Duplicate of #688

**Closed as completed** 2017-03-29 15:10 UTC
Labels: Duplicate, Fixed, P3: Incorrect behavior that affects gameplay, Phase 3, Team 18
