### ISSUE TITLE
Discarding modal not showing up unless sending a chat

### ISSUE THREAD

**Issue by melanie38** [cs340tabyu/cs340Winter2017#704] opened 2016-11-18 20:34 UTC
I rolled a 7, the discard model didn't pop up until I sent a message in the chat.

**Comment by Chroniclerz** [comment] 2016-11-18 21:14
Duplicate of the #700 . Same root issue (exception getting thrown). Both resolved

**Closed as completed** 2016-11-22 17:45 UTC
Labels: Duplicate, P3: Incorrect behavior that affects gameplay, Phase 3, TA-Fixed, Team 8
