### ISSUE TITLE
Frozen after Discard - lost map

### ISSUE THREAD

**Issue by wiseman5** [cs340tabyu/cs340Winter2017#402] opened 2016-10-27 04:03 UTC
After I discarded the game was stuck waiting.  I tried to log out and back in but it was still stuck waiting and the map had disappeared.

![image](https://cloud.githubusercontent.com/assets/16614336/19754126/e7945e8e-9bc7-11e6-887d-440daabd7dc7.png)

**Comment by intcreator** [comment] 2016-10-28 18:35
Duplicate of #316.

**Closed as completed by intcreator** 2016-10-28 18:35 UTC
Labels: Duplicate, P2: Blocking gameplay, Phase 2, Team 12
