### ISSUE TITLE
Solder moves robber twice

### ISSUE THREAD

**Issue by derbraun** [cs340tabyu/cs340Winter2017#412] opened 2016-10-27 04:16 UTC

**Comment by jbskaggs** [comment] 2016-10-27 19:21
I can't reproduce this error when I play a soldier card everything works swimmingly.  Could you please include steps to reproduce?

**Comment by derbraun** [comment] 2016-10-28 00:08
Some how, The robber was moved, and then the log showed that a solder was played even though the player had no dev cards. The robber was moved, and then it showed up again asking to move the robber. So the log said, <Player> rolled a 7 -> <Player moved the robber and robbed <other player>  -> <Player> used a solder -> <Player> robbed <another player> -> <Player> robbed <yet another player>.  Unfortunately, I didn't take a screen shot of it to show you.

**Comment by xandroxygen** [comment] 2016-10-28 21:16
From your comment, this sounds like this is a duplicate of #411 ? Have you been able to reproduce it at all?

**Comment by xandroxygen** [comment] 2016-10-29 17:27
See #412 for invalid reason

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Invalid, P3: Incorrect behavior that affects gameplay, Phase 2, TA-Fixed, Team 5
