### ISSUE TITLE
Domestic Trade Controller freezes when the trading with normal player

### ISSUE THREAD

**Issue by derbraun** [cs340tabyu/cs340Winter2017#314] opened 2016-10-27 02:15 UTC
When submitting a domestic trade request to a non-AI  player, the Wait for Player screen appears and does not go away even though the log shows that the player rejected the trade. Only way to clear is to leave the game and then log back into it, or to resize it. Can still end turn with it up though.

**Comment by xandroxygen** [comment] 2016-10-27 15:37
Unable to reproduce.

Logged in as Pete
Made trade with Mark
Logged in as Mark
Declined Trade
Pete's screen went back to normal. 

marking as invalid.

**Comment by xandroxygen** [comment] 2016-10-29 18:48
Regardless, fix for #309 should take care of this anyways.

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Invalid, P3: Incorrect behavior that affects gameplay, Phase 2, TA-Fixed, Team 5
