### ISSUE TITLE
[Group 14] [P3] You can purchase unlimited development cards without the required resources.

### ISSUE THREAD

**Issue by janderson11** [cs340tabyu/cs340Winter2017#341] opened 2016-10-27 02:52 UTC
Buying development cards reduces the correct resource types, but your not restricted from buying them if you don't have enough resources.

**Comment by daviscodesbugs** [comment] 2016-10-29 17:41
Playing the version of the code that was submitted, every dev card that is purchased decrements the proper resources. And if there are not sufficient resources to buy a dev card, the button does not function (it is grayed out).

**Comment by daviscodesbugs** [comment] 2016-10-29 17:52
We figured it out, when you have sufficient resources, but it's not your turn, if you hit the buy dev card button, then it purchases a dev card, but gives it to the player who's turn it is. This is a symptom of the bug where you can take actions when it's not your turn (such as hitting end turn over and over).

Duplicate of #476.

**Closed as completed** 2016-10-29 17:55 UTC
Labels: Duplicate, P3: Incorrect behavior that affects gameplay, Phase 2, Team 14
