### ISSUE TITLE
Can build 2 settlements on the same port

### ISSUE THREAD

**Issue by parkji03** [cs340tabyu/cs340Winter2017#257] opened 2016-10-27 00:18 UTC
built 2 settlements on the same port during 1st round and 2nd round

**Comment by kupiakos** [comment] 2016-10-31 15:30
Arguably a duplicate of everything involving incorrect placement of settlements.

**Comment by kupiakos** [comment] 2016-11-02 20:19
Duplicate of #237

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 3
