### ISSUE TITLE
Turn tracker color off

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#258] opened 2016-10-27 00:19 UTC
Turn Tracker color not updated currently when player color changed
![bug13](https://cloud.githubusercontent.com/assets/22157895/19749745/b4019060-9ba8-11e6-8084-d01a01acbada.png)

**Comment by UnoriginalElephant** [comment] 2016-10-28 00:32
duplicate of #255

**Comment by Chroniclerz** [comment] 2016-10-28 00:36
Similar, and possibly in reference to the same core issue, but its specifically referring to the Turn tracker being multi-colored as per the bottom left corner.

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Duplicate, Fixed, P5: Stylistic or other minor error, Phase 2, Team 9
