### ISSUE TITLE
Initial resources not given

### ISSUE THREAD

**Issue by smbrown1** [cs340tabyu/cs340Winter2017#727] opened 2016-11-18 21:05 UTC
After building initial settlements, each player should get some resources, but don't

![image](https://cloud.githubusercontent.com/assets/14623878/20446641/fe699156-ad97-11e6-98e3-b0e33a300026.png)

**Comment by phhorton** [comment] 2016-11-21 21:29
Duplicate of Issue #720

**Closed as completed** 2017-03-29 15:10 UTC
Labels: Duplicate, P3: Incorrect behavior that affects gameplay, Phase 3, Team 3
