### ISSUE TITLE
Setup phase with multiple clients: clients could start setting up when it wasn't their turn

### ISSUE THREAD

**Issue by StephBrown923** [cs340tabyu/cs340Winter2017#321] opened 2016-10-27 02:23 UTC
For example, client 1 was able to build a road and settlement when it should have been client 0 first and then client 1.
And the AIs never placed their pieces during setup phase

**Comment by intcreator** [comment] 2016-10-28 19:03
Duplicate of #335.

**Closed as completed by intcreator** 2016-10-28 19:03 UTC
Labels: Duplicate, P3: Incorrect behavior that affects gameplay, Phase 2, Team 12
