### ISSUE TITLE
Creating a game doesn't join you to that game automatically

### ISSUE THREAD

**Issue by klew91** [cs340tabyu/cs340Winter2017#656] opened 2016-11-18 19:43 UTC

**Comment by irbishop** [comment] 2016-11-19 00:44
Can you provide more information?  Do you show up as being player in the game list and you have to click re-join?  If so that is correct behavior.

**Comment by irbishop** [comment] 2016-11-19 07:19
This sounds like a duplicate of #633, which is invalid

**Closed as completed by irbishop** 2016-11-19 07:19 UTC
Labels: Invalid, P4: Incorrect behavior that doesn't affect gameplay, Phase 3, Team 18
