### ISSUE TITLE
Robbing displays option to rob self

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#251] opened 2016-10-27 00:14 UTC
Robbing displays option to rob self
![bug8](https://cloud.githubusercontent.com/assets/22157895/19749674/0d45fd1a-9ba8-11e6-99d0-cb91c58c9f77.png)

**Comment by UnoriginalElephant** [comment] 2016-10-28 00:46
duplicate of #263 ?

**Comment by Chroniclerz** [comment] 2016-10-28 00:49
Different. In this case the robber was placed next to his own settlement, and opened option to rob himself. In the other #263 the Robber was adjacent to no settlements/cities and still opened up a window. I forget the details, but it might have been the last Robber's options.

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Duplicate, Fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 9
