### ISSUE TITLE
Displays "can place settlement" in setup round for sea hexes

### ISSUE THREAD

**Issue by Chroniclerz** [cs340tabyu/cs340Winter2017#243] opened 2016-10-27 00:09 UTC
In the setup phase the interface allows the user to attempt to place settlements around Sea Hexes
![bug3](https://cloud.githubusercontent.com/assets/22157895/19749593/664d4ee6-9ba7-11e6-99a6-bb82d5896465.png)

**Comment by UnoriginalElephant** [comment] 2016-10-28 14:46
duplicate of #244

**Closed as completed** 2016-11-16 23:05 UTC
Labels: Duplicate, Fixed, P3: Incorrect behavior that affects gameplay, Phase 2, Team 9
